version: '3.7'

services:
  puppet:
    environment:
      - DNS_ALT_NAMES=puppet,${DNS_ALT_NAMES:-}
    volumes:
      - puppetserver-enc:/etc/puppetlabs/enc/
      - puppetserver-r10k:/etc/puppetlabs/r10k/
volumes:
  puppetserver-enc:
  puppetserver-r10k:
